# Generated by Django 6.0.4 on 2026-04-16 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimHealthLabel',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=20, unique=True)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color_hex', models.CharField(default='#6366F1', max_length=7)),
            ],
            options={
                'db_table': 'dim_health_label',
                'ordering': ['-min_score'],
            },
        ),
        migrations.CreateModel(
            name='DimSector',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=100, unique=True)),
                ('sector_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color_hex', models.CharField(default='#6366F1', max_length=7)),
            ],
            options={
                'db_table': 'dim_sector',
                'ordering': ['sector_name'],
            },
        ),
        migrations.CreateModel(
            name='DimYear',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_label', models.CharField(max_length=20, unique=True)),
                ('fiscal_year', models.IntegerField(null=True)),
                ('quarter', models.CharField(blank=True, default='', max_length=5)),
                ('is_ttm', models.BooleanField(default=False)),
                ('is_half_year', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dim_year',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DimCompany',
            fields=[
                ('symbol', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('sub_sector', models.CharField(blank=True, default='', max_length=100)),
                ('company_logo', models.URLField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('nse_url', models.URLField(blank=True, default='')),
                ('bse_url', models.URLField(blank=True, default='')),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('roce_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roe_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('about_company', models.TextField(blank=True, default='')),
                ('market_cap_cr', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='warehouse.dimsector')),
            ],
            options={
                'db_table': 'dim_company',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(default='Annual Report', max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.dimcompany')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.dimyear')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='FactMLScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profitability_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('growth_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('leverage_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cashflow_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dividend_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('trend_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_scores', to='warehouse.dimcompany')),
                ('health_label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='warehouse.dimhealthlabel')),
            ],
            options={
                'db_table': 'fact_ml_scores',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='FactProsCons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_pro', models.BooleanField()),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('text', models.TextField()),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('ML', 'ML Generated')], default='MANUAL', max_length=10)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros_cons', to='warehouse.dimcompany')),
            ],
            options={
                'db_table': 'fact_pros_cons',
            },
        ),
        migrations.CreateModel(
            name='FactAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_label', models.CharField(max_length=10)),
                ('compounded_sales_growth_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('compounded_profit_growth_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('stock_price_cagr_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roe_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='warehouse.dimcompany')),
            ],
            options={
                'db_table': 'fact_analysis',
                'unique_together': {('company', 'period_label')},
            },
        ),
        migrations.CreateModel(
            name='FactBalanceSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equity_capital', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('reserves', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('borrowings', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('other_liabilities', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('fixed_assets', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('cwip', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('other_assets', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('debt_to_equity', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('equity_ratio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='warehouse.dimcompany')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='warehouse.dimyear')),
            ],
            options={
                'db_table': 'fact_balance_sheet',
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FactCashFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operating_activity', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('investing_activity', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('financing_activity', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('free_cash_flow', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='warehouse.dimcompany')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='warehouse.dimyear')),
            ],
            options={
                'db_table': 'fact_cash_flow',
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FactProfitLoss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('opm_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('other_income', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('profit_before_tax', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('tax_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dividend_payout_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('net_profit_margin_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('expense_ratio_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('interest_coverage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss', to='warehouse.dimcompany')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss', to='warehouse.dimyear')),
            ],
            options={
                'db_table': 'fact_profit_loss',
                'unique_together': {('company', 'year')},
            },
        ),
    ]
